// <auto-generated />
using System;
using CoralLedger.Blue.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoralLedger.Blue.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MarineDbContext))]
    [Migration("20260201101550_AddPatrolRoutes")]
    partial class AddPatrolRoutes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("VesselId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("MarineProtectedAreaId");

                    b.HasIndex("Severity");

                    b.HasIndex("Type");

                    b.HasIndex("VesselId");

                    b.HasIndex("Type", "CreatedAt");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<TimeSpan>("CooldownPeriod")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NotificationChannels")
                        .HasColumnType("integer");

                    b.Property<string>("NotificationEmails")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("MarineProtectedAreaId");

                    b.HasIndex("Type");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.BahamianSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConservationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Habitat")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdentificationTips")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsInvasive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LocalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("TypicalDepthMaxM")
                        .HasColumnType("integer");

                    b.Property<int?>("TypicalDepthMinM")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CommonName");

                    b.HasIndex("ConservationStatus");

                    b.HasIndex("IsInvasive");

                    b.HasIndex("LocalName");

                    b.HasIndex("ScientificName")
                        .IsUnique();

                    b.ToTable("bahamian_species", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.BleachingAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("DegreeHeatingWeek")
                        .HasPrecision(8, 3)
                        .HasColumnType("double precision");

                    b.Property<double?>("HotSpot")
                        .HasPrecision(6, 3)
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReefId")
                        .HasColumnType("uuid");

                    b.Property<double>("SeaSurfaceTemperature")
                        .HasPrecision(6, 3)
                        .HasColumnType("double precision");

                    b.Property<double>("SstAnomaly")
                        .HasPrecision(6, 3)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AlertLevel");

                    b.HasIndex("Date");

                    b.HasIndex("DegreeHeatingWeek");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("ReefId");

                    b.HasIndex("Date", "AlertLevel");

                    b.HasIndex("MarineProtectedAreaId", "Date");

                    b.ToTable("bleaching_alerts", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.CitizenObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CitizenEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CitizenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool?>("IsInMpa")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModerationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ObservationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReefId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("MarineProtectedAreaId");

                    b.HasIndex("ObservationTime");

                    b.HasIndex("ReefId");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("citizen_observations", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.MarineProtectedArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaSquareKm")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<Geometry>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<Geometry>("BoundarySimplifiedDetail")
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<Geometry>("BoundarySimplifiedLow")
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<Geometry>("BoundarySimplifiedMedium")
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("DesignationDate")
                        .HasColumnType("date");

                    b.Property<string>("IslandGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LocalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ManagingAuthority")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProtectionLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WdpaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("WdpaLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.HasIndex("Centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "GIST");

                    b.HasIndex("IslandGroup");

                    b.HasIndex("Name");

                    b.HasIndex("ProtectionLevel");

                    b.HasIndex("WdpaId")
                        .IsUnique();

                    b.ToTable("marine_protected_areas", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.NLQAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataSourcesUsed")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GeneratedSql")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("InterpretedAs")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OriginalQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("QueryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiredDisambiguation")
                        .HasColumnType("boolean");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<bool>("SecurityRestrictionApplied")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("Id");

                    b.HasIndex("Persona");

                    b.HasIndex("QueryTime");

                    b.HasIndex("SecurityRestrictionApplied");

                    b.HasIndex("Status");

                    b.ToTable("nlq_audit_logs", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.ObservationPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BlobUri")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CitizenObservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CitizenObservationId");

                    b.HasIndex("UploadedAt");

                    b.ToTable("observation_photos", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.PatrolRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OfficerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OfficerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RecordingIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<LineString>("RouteGeometry")
                        .HasColumnType("geometry(LineString, 4326)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("TotalDistanceMeters")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MarineProtectedAreaId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("RouteGeometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RouteGeometry"), "GIST");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.ToTable("patrol_routes", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.PatrolRoutePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("PatrolRouteId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("PatrolRouteId");

                    b.HasIndex("Timestamp");

                    b.ToTable("patrol_route_points", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.PatrolWaypoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PatrolRouteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WaypointType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("PatrolRouteId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("WaypointType");

                    b.ToTable("patrol_waypoints", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.Reef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("BleachingPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("CoralCoverPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<double?>("DepthMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("LastSurveyDate")
                        .HasColumnType("date");

                    b.Property<double?>("LengthKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<Geometry>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HealthStatus");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("MarineProtectedAreaId");

                    b.HasIndex("Name");

                    b.ToTable("reefs", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.SpeciesMisidentificationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectedScientificName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("CorrectedSpeciesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IncorrectScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReporterEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ReporterName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SpeciesObservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CorrectedSpeciesId");

                    b.HasIndex("Expertise");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("SpeciesObservationId");

                    b.HasIndex("Status");

                    b.ToTable("species_misidentification_reports", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.SpeciesObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AiConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<Guid>("BahamianSpeciesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CitizenObservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresExpertVerification")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BahamianSpeciesId");

                    b.HasIndex("IdentifiedAt");

                    b.HasIndex("IsAiGenerated");

                    b.HasIndex("RequiresExpertVerification");

                    b.HasIndex("CitizenObservationId", "BahamianSpeciesId");

                    b.ToTable("species_observations", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallSign")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("GearType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GfwVesselId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Imo")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastPositionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LengthMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Mmsi")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("TonnageGt")
                        .HasPrecision(12, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("VesselType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Flag");

                    b.HasIndex("GfwVesselId");

                    b.HasIndex("Imo");

                    b.HasIndex("IsActive");

                    b.HasIndex("Mmsi");

                    b.HasIndex("Name");

                    b.HasIndex("VesselType");

                    b.ToTable("vessels", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.VesselEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<double?>("DistanceKm")
                        .HasPrecision(10, 3)
                        .HasColumnType("double precision");

                    b.Property<double?>("DurationHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("EncounterVesselId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GfwEventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsInMpa")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PortName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("GfwEventId");

                    b.HasIndex("IsInMpa");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("MarineProtectedAreaId");

                    b.HasIndex("StartTime");

                    b.HasIndex("VesselId");

                    b.HasIndex("VesselId", "EventType", "StartTime");

                    b.ToTable("vessel_events", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.VesselPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CourseOverGround")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<double?>("DistanceFromShoreKm")
                        .HasPrecision(10, 3)
                        .HasColumnType("double precision");

                    b.Property<double?>("Heading")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsInMpa")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<double?>("SpeedKnots")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsInMpa");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("MarineProtectedAreaId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VesselId");

                    b.HasIndex("VesselId", "Timestamp");

                    b.ToTable("vessel_positions", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.Alert", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.AlertRule", "AlertRule")
                        .WithMany("Alerts")
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoralLedger.Blue.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany()
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoralLedger.Blue.Domain.Entities.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AlertRule");

                    b.Navigation("MarineProtectedArea");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.AlertRule", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany()
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MarineProtectedArea");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.BleachingAlert", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany()
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoralLedger.Blue.Domain.Entities.Reef", "Reef")
                        .WithMany()
                        .HasForeignKey("ReefId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MarineProtectedArea");

                    b.Navigation("Reef");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.CitizenObservation", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany()
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoralLedger.Blue.Domain.Entities.Reef", "Reef")
                        .WithMany()
                        .HasForeignKey("ReefId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MarineProtectedArea");

                    b.Navigation("Reef");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.ObservationPhoto", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.CitizenObservation", "CitizenObservation")
                        .WithMany("Photos")
                        .HasForeignKey("CitizenObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CitizenObservation");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.PatrolRoute", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany()
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MarineProtectedArea");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.PatrolRoutePoint", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.PatrolRoute", "PatrolRoute")
                        .WithMany("Points")
                        .HasForeignKey("PatrolRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolRoute");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.PatrolWaypoint", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.PatrolRoute", "PatrolRoute")
                        .WithMany("Waypoints")
                        .HasForeignKey("PatrolRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolRoute");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.Reef", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany("Reefs")
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MarineProtectedArea");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.SpeciesMisidentificationReport", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.BahamianSpecies", "CorrectedSpecies")
                        .WithMany()
                        .HasForeignKey("CorrectedSpeciesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoralLedger.Blue.Domain.Entities.SpeciesObservation", "SpeciesObservation")
                        .WithMany()
                        .HasForeignKey("SpeciesObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorrectedSpecies");

                    b.Navigation("SpeciesObservation");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.SpeciesObservation", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.BahamianSpecies", "BahamianSpecies")
                        .WithMany("Observations")
                        .HasForeignKey("BahamianSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoralLedger.Blue.Domain.Entities.CitizenObservation", "CitizenObservation")
                        .WithMany()
                        .HasForeignKey("CitizenObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BahamianSpecies");

                    b.Navigation("CitizenObservation");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.VesselEvent", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany()
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoralLedger.Blue.Domain.Entities.Vessel", "Vessel")
                        .WithMany("Events")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarineProtectedArea");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.VesselPosition", b =>
                {
                    b.HasOne("CoralLedger.Blue.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany()
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoralLedger.Blue.Domain.Entities.Vessel", "Vessel")
                        .WithMany("Positions")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarineProtectedArea");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.AlertRule", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.BahamianSpecies", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.CitizenObservation", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.MarineProtectedArea", b =>
                {
                    b.Navigation("Reefs");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.PatrolRoute", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("Waypoints");
                });

            modelBuilder.Entity("CoralLedger.Blue.Domain.Entities.Vessel", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
