// <auto-generated />
using System;
using CoralLedger.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoralLedger.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MarineDbContext))]
    [Migration("20251204023304_AddCitizenObservations")]
    partial class AddCitizenObservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoralLedger.Domain.Entities.BleachingAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("DegreeHeatingWeek")
                        .HasPrecision(8, 3)
                        .HasColumnType("double precision");

                    b.Property<double?>("HotSpot")
                        .HasPrecision(6, 3)
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReefId")
                        .HasColumnType("uuid");

                    b.Property<double>("SeaSurfaceTemperature")
                        .HasPrecision(6, 3)
                        .HasColumnType("double precision");

                    b.Property<double>("SstAnomaly")
                        .HasPrecision(6, 3)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AlertLevel");

                    b.HasIndex("Date");

                    b.HasIndex("DegreeHeatingWeek");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("ReefId");

                    b.HasIndex("Date", "AlertLevel");

                    b.HasIndex("MarineProtectedAreaId", "Date");

                    b.ToTable("bleaching_alerts", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.CitizenObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CitizenEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CitizenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool?>("IsInMpa")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModerationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ObservationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReefId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("MarineProtectedAreaId");

                    b.HasIndex("ObservationTime");

                    b.HasIndex("ReefId");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("citizen_observations", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.MarineProtectedArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaSquareKm")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<Geometry>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<Geometry>("BoundarySimplifiedLow")
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<Geometry>("BoundarySimplifiedMedium")
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("DesignationDate")
                        .HasColumnType("date");

                    b.Property<string>("IslandGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LocalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ManagingAuthority")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProtectionLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WdpaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("WdpaLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.HasIndex("Centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "GIST");

                    b.HasIndex("IslandGroup");

                    b.HasIndex("Name");

                    b.HasIndex("ProtectionLevel");

                    b.HasIndex("WdpaId")
                        .IsUnique();

                    b.ToTable("marine_protected_areas", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.ObservationPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BlobUri")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CitizenObservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CitizenObservationId");

                    b.HasIndex("UploadedAt");

                    b.ToTable("observation_photos", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.Reef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("BleachingPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("CoralCoverPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<double?>("DepthMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("LastSurveyDate")
                        .HasColumnType("date");

                    b.Property<double?>("LengthKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<Geometry>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HealthStatus");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("MarineProtectedAreaId");

                    b.HasIndex("Name");

                    b.ToTable("reefs", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallSign")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("GearType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GfwVesselId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Imo")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastPositionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LengthMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Mmsi")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("TonnageGt")
                        .HasPrecision(12, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("VesselType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Flag");

                    b.HasIndex("GfwVesselId");

                    b.HasIndex("Imo");

                    b.HasIndex("IsActive");

                    b.HasIndex("Mmsi");

                    b.HasIndex("Name");

                    b.HasIndex("VesselType");

                    b.ToTable("vessels", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.VesselEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<double?>("DistanceKm")
                        .HasPrecision(10, 3)
                        .HasColumnType("double precision");

                    b.Property<double?>("DurationHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("EncounterVesselId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GfwEventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsInMpa")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PortName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("GfwEventId");

                    b.HasIndex("IsInMpa");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("MarineProtectedAreaId");

                    b.HasIndex("StartTime");

                    b.HasIndex("VesselId");

                    b.HasIndex("VesselId", "EventType", "StartTime");

                    b.ToTable("vessel_events", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.VesselPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CourseOverGround")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<double?>("DistanceFromShoreKm")
                        .HasPrecision(10, 3)
                        .HasColumnType("double precision");

                    b.Property<double?>("Heading")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsInMpa")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Guid?>("MarineProtectedAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<double?>("SpeedKnots")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsInMpa");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("MarineProtectedAreaId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VesselId");

                    b.HasIndex("VesselId", "Timestamp");

                    b.ToTable("vessel_positions", (string)null);
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.BleachingAlert", b =>
                {
                    b.HasOne("CoralLedger.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany()
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoralLedger.Domain.Entities.Reef", "Reef")
                        .WithMany()
                        .HasForeignKey("ReefId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MarineProtectedArea");

                    b.Navigation("Reef");
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.CitizenObservation", b =>
                {
                    b.HasOne("CoralLedger.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany()
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoralLedger.Domain.Entities.Reef", "Reef")
                        .WithMany()
                        .HasForeignKey("ReefId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MarineProtectedArea");

                    b.Navigation("Reef");
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.ObservationPhoto", b =>
                {
                    b.HasOne("CoralLedger.Domain.Entities.CitizenObservation", "CitizenObservation")
                        .WithMany("Photos")
                        .HasForeignKey("CitizenObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CitizenObservation");
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.Reef", b =>
                {
                    b.HasOne("CoralLedger.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany("Reefs")
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MarineProtectedArea");
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.VesselEvent", b =>
                {
                    b.HasOne("CoralLedger.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany()
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoralLedger.Domain.Entities.Vessel", "Vessel")
                        .WithMany("Events")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarineProtectedArea");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.VesselPosition", b =>
                {
                    b.HasOne("CoralLedger.Domain.Entities.MarineProtectedArea", "MarineProtectedArea")
                        .WithMany()
                        .HasForeignKey("MarineProtectedAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoralLedger.Domain.Entities.Vessel", "Vessel")
                        .WithMany("Positions")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarineProtectedArea");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.CitizenObservation", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.MarineProtectedArea", b =>
                {
                    b.Navigation("Reefs");
                });

            modelBuilder.Entity("CoralLedger.Domain.Entities.Vessel", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
