using CoralLedger.Blue.Application.Common.Interfaces;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Quartz;

namespace CoralLedger.Blue.Infrastructure.Jobs;

/// <summary>
/// Scheduled job that generates and emails PDF reports for MPAs
/// Supports weekly and monthly report generation
/// </summary>
[DisallowConcurrentExecution]
public class ScheduledReportJob : IJob
{
    public static readonly JobKey WeeklyReportKey = new("WeeklyReportJob", "Reports");
    public static readonly JobKey MonthlyReportKey = new("MonthlyReportJob", "Reports");

    private readonly IServiceScopeFactory _scopeFactory;
    private readonly ILogger<ScheduledReportJob> _logger;

    public ScheduledReportJob(
        IServiceScopeFactory scopeFactory,
        ILogger<ScheduledReportJob> logger)
    {
        _scopeFactory = scopeFactory;
        _logger = logger;
    }

    public async Task Execute(IJobExecutionContext context)
    {
        var reportType = context.JobDetail.Key.Name; // WeeklyReportJob or MonthlyReportJob
        _logger.LogInformation("Starting {ReportType} at {Time}", reportType, DateTimeOffset.UtcNow);

        using var scope = _scopeFactory.CreateScope();
        var reportService = scope.ServiceProvider.GetRequiredService<IReportGenerationService>();
        var emailService = scope.ServiceProvider.GetRequiredService<IEmailService>();

        try
        {
            // Determine date range based on report type
            var (fromDate, toDate) = GetDateRange(reportType);

            // Generate all-MPAs summary report
            var options = new ReportOptions
            {
                FromDate = fromDate,
                ToDate = toDate,
                IncludeCharts = true
            };

            _logger.LogInformation("Generating {ReportType} PDF for period {FromDate} to {ToDate}",
                reportType, fromDate, toDate);

            var pdfBytes = await reportService.GenerateAllMpasReportAsync(options, context.CancellationToken)
                .ConfigureAwait(false);

            _logger.LogInformation("PDF generated successfully, size: {Size} bytes", pdfBytes.Length);

            // Get recipient email addresses from job data (configured in DependencyInjection)
            var recipients = context.JobDetail.JobDataMap.GetString("Recipients") ?? string.Empty;
            if (string.IsNullOrEmpty(recipients))
            {
                _logger.LogWarning("No recipients configured for {ReportType}, skipping email", reportType);
                return;
            }

            var recipientList = recipients.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .ToList();

            // Send email with PDF attachment
            var subject = $"CoralLedger Blue - {reportType.Replace("Job", "")} Report";
            var body = $@"
                <h2>CoralLedger Blue Marine Protected Areas Report</h2>
                <p>Please find attached the {reportType.Replace("Job", "").ToLower()} summary report for all MPAs.</p>
                <p><strong>Report Period:</strong> {fromDate:yyyy-MM-dd} to {toDate:yyyy-MM-dd}</p>
                <p>This automated report includes:</p>
                <ul>
                    <li>Overview of all Marine Protected Areas</li>
                    <li>Coral bleaching alerts and heat stress data</li>
                    <li>Fishing vessel activity and enforcement events</li>
                    <li>Citizen science observations</li>
                    <li>Statistical summaries and trends</li>
                </ul>
                <p>For more detailed information, please visit the CoralLedger Blue platform.</p>
                <hr>
                <p style='font-size: 0.9em; color: #666;'>
                    This is an automated report generated by CoralLedger Blue.<br>
                    Report generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC
                </p>
            ";

            var fileName = $"coralledger-{reportType.Replace("Job", "").ToLower()}-{DateTime.UtcNow:yyyyMMdd}.pdf";

            foreach (var recipient in recipientList)
            {
                _logger.LogInformation("Sending {ReportType} to {Recipient}", reportType, recipient);

                await emailService.SendEmailWithAttachmentAsync(
                    recipient,
                    subject,
                    body,
                    pdfBytes,
                    fileName,
                    "application/pdf",
                    context.CancellationToken).ConfigureAwait(false);
            }

            _logger.LogInformation("Successfully completed {ReportType}, sent to {Count} recipients",
                reportType, recipientList.Count);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error executing {ReportType}", reportType);
            throw; // Re-throw to trigger Quartz retry policy if configured
        }
    }

    private static (DateTime fromDate, DateTime toDate) GetDateRange(string reportType)
    {
        var now = DateTime.UtcNow;
        var toDate = now.Date; // End of yesterday (inclusive)

        if (reportType.Contains("Weekly", StringComparison.OrdinalIgnoreCase))
        {
            // Last 7 days
            var fromDate = toDate.AddDays(-7);
            return (fromDate, toDate);
        }
        else if (reportType.Contains("Monthly", StringComparison.OrdinalIgnoreCase))
        {
            // Last month
            var fromDate = new DateTime(now.Year, now.Month, 1).AddMonths(-1);
            var lastDayOfMonth = new DateTime(now.Year, now.Month, 1).AddDays(-1);
            return (fromDate, lastDayOfMonth);
        }
        else
        {
            // Default to last 7 days
            var fromDate = toDate.AddDays(-7);
            return (fromDate, toDate);
        }
    }
}
